<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "spiribox"
 *
 * Auto generated by Extension Builder 2016-05-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SpiriBox',
	'description' => 'SpiriBox stellt Bibelzitate bereit. Diese können im Frontend per Formular erstellt werden und im Backend über Datensätze gepflegt werden. Außerdem gibt es eine Gesamtansicht aller Datensätze für das Frontend.',
	'category' => 'plugin',
	'author' => 'Michel Blumenstein',
	'author_email' => 'michel@kinra.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'fileadmin/user_upload/spiribox',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1a',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);